### PR TITLE
Add workflow for deploying development branch to Heroku staging instance

### PR DESCRIPTION
**Pull request by lottspot**

### CODE REVIEW

**Comment by themightychris** [comment]
@lottspot looks good to me at first sight, have you been able to take this for a spin yet for real in GH Actions? I'd like to see a test run before we merge.

The process for testing out GH Actions, since they only run from a repo's default branch, is to:

1. fork this repo into your personal account
2. go to the actions tab and turn on actions (if you make any commits to your default branch before you turn on actions, you'll need to make another commit or just amend and force push to trigger actions)
3. merge your changes into your repo's `develop` branch
4. make commits right to develop, or amend and force-push to iterate
5. rebase and push your commits to your feature branch

**Comment by themightychris** [comment]
@lottspot another protip for testing/debugging actions: throw the [tmate action](https://github.com/mxschmitt/action-tmate) in as a step after your environment is set up and you get a shell you can step into

**Review by themightychris — CHANGES_REQUESTED** [review]
What I'm looking for in reviewing.a GH workflow change is a link to the run log from it working on the main branch of your fork

**Comment by quinn-dougherty** [comment]
closes https://github.com/CodeForPhilly/chime/issues/66

**Comment by lottspot** [comment]
@themightychris Thanks for the testing tip! I went with that method and was able to complete a successful test run on my own fork:

https://github.com/lottspot/chime/runs/531767918?check_suite_focus=true

And it looks like it deployed the develop branch of my fork at: https://cfp-ci-chime.herokuapp.com/

**Review by themightychris — APPROVED** [review]

**Pull request merged**
