### PR TITLE
Install black

### PR DESCRIPTION
**Pull request by grahamalama**
Addresses issue https://github.com/CodeForPhilly/chime/issues/193

This PR:
- Adds [`black`](https://github.com/psf/black)
- Adds a script `script/format` to run black on the correct files
- Runs black as a part of the `Lint and Test` workflow

I then ran `black` and committed the changes that it made.

Also, I noticed that `pytest` was in the `[dependencies]` section of the `Pipfile`, so when I added `black` to the dev dependencies, I moved `pytest` there was well.

Unrelated to this PR (I believe), the `Cypress` step is failing in the `Lint and Test` workflow. From what I could tell in Slack, that's a know issue. Possibly related to this failure, I saw [this notice](https://github.com/cypress-io/github-action#important) in the `cypress-io/github-action` repo.

### CODE REVIEW

**Review by themightychris — CHANGES_REQUESTED** [review]
@grahamalama I think you should pull all the formatting changes out of here, and focus this PR on just adding the tooling and the workflow. Including the formatting changes at the same time is going to create a hellscape of merge conflicts with other outstanding work

I feel like the best strategy would be to get the format script merged, and then have applying the formatting across the codebase be a final commit right before the next major release after all other PRs tagged to that release get merged. Then any PRs outstanding after that will need to get rebased with the format script applied to each commit for cleanest merge results

**Comment by quinn-dougherty** [comment]
> I think you should pull all the formatting changes out of here, and focus this PR on just adding the tooling and the workflow. Including the formatting changes at the same time is going to create a hellscape of merge conflicts with other outstanding work

I fully agree with Chris!

**Comment by quinn-dougherty** [comment]
also @grahamalama  i'm just realizing this is against `dash` branch, we want it to be against `develop`.

**Comment by quinn-dougherty** [comment]
w/r/t Chris' comments i think i'm gonna close this

**Comment by themightychris** [comment]
Please do open a new PR adding the workflow to `develop` @grahamalama !

**Comment by grahambeckley** [comment]
Great points @themightychris, and makes sense. I wasn't fully aware of the release cycle / how commits like this would be merged. I'll definitely open another PR for thi

**Comment by grahamalama** [comment]
Great points @themightychris, and makes sense. I wasn't fully aware of the release cycle / how commits like this would be merged. I'll definitely open another PR for this

**Pull request closed without merging**
