### PR TITLE
As presumed infection counts rise, don't count them as additional to population

### LINKED ISSUE #211: Conflation of regional population with susceptible population is wrong with large infection count
The raw data shows a total of S+I+R that is larger than the user-provided regional population. This is because the number presumed initially infected based on hospitalization rate isn't subtracted from the population to compute the currently susceptible.

### PR DESCRIPTION
**Pull request by PhilMiller**
This was barely noticeable when the given value of Current Hospitalizations was small, and hence the implied number of initial infections was also small. With projections now being done from much larger numbers of present cases, seeing the ultimate Recovered count much larger than the provided population looks really bad.

Fixes #211

### CODE REVIEW

**Comment by mdbecker** [comment]
This will need to be reviewed by @cjbayesian or myself. Thanks @PhilMiller ! Keep the good work coming!

**Review by cjbayesian — COMMENTED** [review]
This is a good catch. However, it also highlights to me another, related issue which is that this assumes that no-one is yet recovered.

**Comment by cjbayesian** [comment]
It seems like much like #206, the full solution is to start the sim from a low # infected and line up the projections to current inputed conditions.

**Comment by mdbecker** [comment]
@PhilMiller let us know if this is something you feel comfortable tackling. Based on Corey's comments it feels like it could be a bit tricky to think through and get right. One assumption you would have to make is the date when the first infection happened. For the purposes of this ticket maybe come up with a reasonable anchor date that will work for most users? Maybe make this an extra parameter so that the users can modify it? If you add another parameter to the sidebar for this I recommend putting it near the bottom. Something like "Days since first infection". Thoughts?

**Review by mdbecker — CHANGES_REQUESTED** [review]
See comments on ticket

**Comment by PhilMiller** [comment]
I think it still makes sense to get this kind of minimal fix in place sooner rather than later, so that people don't keep bumping into it and asking what's up, a la #229. I'll re-apply the change on the refactored code and re-push.

On the bigger model evolution, give me a day or so. I'll talk it over with you all, but I need to rest this evening.

**Comment by PhilMiller** [comment]
Also, I think most places that are going to be using this are still, for now, in a regime where `R[day 0] ~= 0` is still a reasonable approximation.

**Comment by PhilMiller** [comment]
Replaced as #276

**Pull request closed without merging**
