### PR TITLE
Fix for plateauing y-axis on graphs

### PR DESCRIPTION
**Pull request by kmid5280**
Issue #228 fix. Set values of y_scale.clam to False. Y-axis no longer plateaus when this value is set. @nickcanz I attempted your suggestion on this, but it wouldn't recognize the "clip" property, only the "clamp" property.

### CODE REVIEW

**Comment by nickcanz** [comment]
@kmid5280 the default is "clip", so another option would be to just delete the `clamp` lines entirely and it will go back to the default.

**Comment by kmid5280** [comment]
@nickcanz Do you happen to know why it was set to "True" in the first place? There must have been a reason.

**Comment by nickcanz** [comment]
I set it to `True` just because I thought it looked better 😄 But @mdbecker's judgement is better than mine!

**Comment by kmid5280** [comment]
@nickcanz Got it. I just didn't want to break anything. :)

**Review by pjhoberman — APPROVED** [review]

**Comment by kmid5280** [comment]
Don't merge this yet, I made a mistake.

**Comment by kmid5280** [comment]
I attempted to implement a slider bar that lets the user select the day intervals on the projected admissions and census tables. Unfortunately I ended up pushing those changes into this PR whereas I meant to put them in a separate one. If you like the slider bar and want to keep it then you can piggyback it in with this PR, otherwise I can revert it to the original issue.

**Comment by quinn-dougherty** [comment]
i saw the extra feature and i like it! it allows the user to select the granularity they want in the table.

**Pull request merged**
