### PR TITLE
Make census counts inclusive over the relevant lengths of stay

### LINKED ISSUE #385: ["model"] Census for hospital and icu are not inclusive of longer LOS for (respectively) icu and ventilator
### Summary

From Slack:

civicanalyst Today at 5:06 PM
> Hi all, When I run CHIME for one of our hospitals in PA using the assumption that 30% of hospitalizations will need ICU and Vent along with the assumption that LOS of Vent > LOS ICU, the census curves for Vent is above the ICU case. I understand from documentation that Vent should be a subset of ICU and maybe higher LOS is affecting that? Has this already been discussed here or any thoughts on why that might be happening?

philmiller
> I think I see an underlying mistake in how we’re calculating the census for inpatient relative to icu, and icu relative to vent - admissions categories are inclusive, but we’re not counting a longer stay in the hospital for the portion of patients who end up in critical care

### Suggested fix
Calculate a census of the exclusive values, and then sum them appropriately.

### PR DESCRIPTION
**Pull request by PhilMiller**
Fixes: #385

### CODE REVIEW

**Comment by PhilMiller** [comment]
This removes the abstraction of the enumerated dispositions in the census calculation, instead baking in the specific categories. That may be undesirable.

This also changes the model fits, and hence the 'right' values in the tests. I've not checked them, nor am I particularly qualified to actually update them. Perhaps the primary tests should be written in terms of the time and height of the forecast peaks, so that there's at least some consistency over time, and we have a clear understanding of what it means when we change a value in the test suite.

**Comment by misken** [comment]
In the computation of `census_icu` should it be using `icu_admissions_exclusive` instead of `admits_df.icu`? Seems like `icu_admissions_exclusive` is being calculated but never used.

**Comment by PhilMiller** [comment]
Yes, yes it should.

**Comment by PhilMiller** [comment]
That makes the test failure numbers much closer than they were before, which is heartening.

**Comment by misken** [comment]
@PhilMiller Finally had time to start to look at this. Noticed that last line in admits_df not getting filled in this branch. There's an off by 1 difference between develop and this branch in `build_admits_df` :

`admits_df = dispositions_df.iloc[:-1, :] - dispositions_df.shift(1)  # in this branch`
`admits_df = dispositions_df.iloc[:, :] - dispositions_df.shift(1)  # In develop`

Unfortunately, tests still fail. I'll try to look more closely tomorrow.

**Comment by misken** [comment]
@PhilMiller I think there are two issues. 1) The off by 1 error I mentioned in previous comment is what is causing the admits to not match. I'm running tests on individual data Series equality to find this. When using `admits_df = dispositions_df.iloc[:, :] - dispositions_df.shift(1)`, then the admits match but then equality of census fails. New approach gives higher census - but, I think new approach is right. So, ...

2) After going through your new census calculation, I think it's correct and that the original census projections are biased low. The reason it's happening, is that, in the current approach, all hospitalizations are getting the ALOS of the hospital. But, a subset of those patients are in the ICU and a subset of those are on vents - both of those subpops having different ALOS values than the overall hospital ALOS.

**Comment by PhilMiller** [comment]
Thanks for the catch on the off-by-one error. I'll patch that up later today.

As for the substantive forecast accuracy, we need more input from the hospital people with access to real data, and maybe from UX folks on guiding users to give inputs that will generate output they'll interpret correctly.

**Comment by misken** [comment]
Agree. If user interprets the input ALOS's correctly, it's all good. One thought I had to help users, and I'm working on this right now, is to compute the implied volumes and ALOS's for the subpops of (1) hospital admits who never used ICU and (2) ICU patients who never used vents. Simple computations and just provides user more feedback on the implications of the rate and ALOS values they entered which might help them better calibrate their inputs.

**Pull request closed without merging**
