### PR TITLE
[dash] Bring number input step, min, and type to parity w/ Streamlit

### PR DESCRIPTION
**Pull request by ecsmyth**
Updates a few number input parameters to bring them inline with the Streamlit version as of PR #283.

### CODE REVIEW

**Comment by ckoerber** [comment]
Thanks for the PR. Seems fine and does what it promises (e.g.,"error" rendered form inputs are now with white border).

One thing one may consider here is increasing the step value for float forms because it also affects the up and down arrows shift amounts (and `FLOAT_INPUT_MIN = 0.001` takes many clicks). It might be more user friendly to set both the minimal value and the shift value to a sensible small number for each input. Does someone have a strong opinion on this?

**Comment by ecsmyth** [comment]
With Dash, we could set step to "any" which will still allow input of precise numbers but will result in the arrows stepping by 1. This wasn't possible in the Streamlit version.

**Comment by ckoerber** [comment]
That sounds like a good idea.

**Review by ckoerber — APPROVED** [review]
Tested locally and solves the issue. Thanks for the update.

**Pull request merged**
