### PR TITLE
issue 110 - separate defaults

### PR DESCRIPTION
**Pull request by quinn-dougherty**
- set all the defaults in `defaults.py` 
- should i factor it so defaults are set in like a `conf/env` sort of file now, or in a future PR?

### CODE REVIEW

**Comment by quinn-dougherty** [comment]
gimme a sec fixing lint

**Comment by quinn-dougherty** [comment]
i'm not 100% sure this 
```### Initial Conditions

- The total size of the susceptible population will be the entire catchment area for Penn Medicine entities (HUP, PAH, PMC, CCH)
  - Delaware = {delaware}
  - Chester = {chester}
  - Montgomery = {montgomery}
  - Bucks = {bucks}
  - Philly = {philly}""".format(
            delaware=delaware,
            chester=chester,
            montgomery=montgomery,
            bucks=bucks,
            philly=philly,
        )
    )
    return None
```
in `presentations.py` is appropriate to make the tool for non-Penn users. 

Can i replace it with `"The total size of the susceptible population is {S_default}"`?

**Comment by quinn-dougherty** [comment]
> Can i replace it with `"The total size of the susceptible population is {S_default}"`?

the issue is that not every user will have county-level data

**Comment by jlubken** [comment]
Maybe use a class instead of constant DEFAULTS.

We can initialize the regions, and frequently updated values inside app.py, but use python default parameters for the other values.

In defaults.py:
```python
from collections import namedtuple

# (0.02, 7) is 2%, 7 days
# be sure to multiply by 100 when using as a default to the pct widgets!
RateLos = namedtuple('RateLos', ('rate', 'length_of_stay'))


class Regions:
    """Warning: May not work as expected."""

    def __init__(self, **kwargs):
        s = 0
        for key, value in kwargs.items():
            setattr(self, value)
            s += value
        self._s = s

    @property
    def s(self):
        return self._s


class Defaults:
    """"Class to store defaults."""

    def __init__(
        self, *,
        region: Regions,
        current_hospitalized: int,
        known_infections: int,
        doubling_time: float = 6.0,
        market_share: float 0.15,
        relative_contact_rate: float = 0.0,
        hospitalized: RateLos = RateLos(rate=0.05, length_of_stay=7),
        icu: RateLos = RateLos(rate=0.02, length_of_stay=9),,
        ventilated: RateLos = RateLos(rate=0.01, length_of_stay=10),
        n_days: int = 60,
    ):
        self.region = region
        self.s = region.s
        self.current_hospitalized = current_hospitalized
        self.known_infections = known_infections
        self.doubling_time = doubling_time
        self.n_days = n_days,
        self.market_share = market_share
        self.relative_contact_rate = relative_contact_rate
        self.hopitalized = hospitalized
        self.icu = icu
        self.ventilated = ventilated
```

In app.py:
```python
from penn_chime.defaults import Defaults, Regions

d = Defaults(
    region=Regions(  # TODO: Ideally this should come from config/env
        delaware=564696,
        chester=519293,
        montgomery=826075,
        bucks=628341,
        philly=1581000,
    ),
    current_hospitalized=4,  # update daily
    known_infections=91,  # update daily
)
```

**Comment by jlubken** [comment]
I'd wait on the config. I can easily see adding a widget that allows the selection of the defaults by state or other region.

**Comment by jlubken** [comment]
Update the use of the pct defaults carefully:
```python
icu_rate = (
    st.sidebar.number_input(
        "ICU %(total infections)", 0.0, 100.0,
        value=d.icu.rate * 100,  # Careful, default is a rate not a pct!
        step=1.0, format="%f"
    )
    / 100.0
)

**Comment by jlubken** [comment]
Maybe just pass the interpolated text:
```python
"""Penn Medicine entities include (HUP, PAH, PMC, CCH)
  - Delaware = {delaware}
  - Chester = {chester}
  - Montgomery = {montgomery}
  - Bucks = {bucks}
  - Philly = {philly}""".format(
            delaware=delaware,
            chester=chester,
            montgomery=montgomery,
            bucks=bucks,
            philly=philly,
        )
    )
```

... into the presentation function as a new `note` parameter?

**Comment by quinn-dougherty** [comment]
I think i want to make a `settings.py` and instantiate the `Constants` object in there, then in the docs we instruct the user to go to `settings.py`

**Comment by quinn-dougherty** [comment]
> Maybe just pass the interpolated text: 

i was thinking `f"county populations are " + "".join(f"{key}={value}" for key,value in defaults.regions.__dict__.items()`

These ` (HUP, PAH, PMC, CCH)` are specific penn branches, right? that text will have to be deleted for general purpose app?

**Comment by jlubken** [comment]
> > Maybe just pass the interpolated text:
> 
> i was thinking `f"county populations are " + "".join(f"{key}={value}" for key,value in defaults.regions.__dict__.items()`
> 
> These ` (HUP, PAH, PMC, CCH)` are specific penn branches, right? that text will have to be deleted for general purpose app?

I like the ```region.__dict__.items()```, but add a note to pass in with the (HUP, PAH, PMC, CCH) text. We're really using the counties as a proxy for the regions served around those hospitals. The note could be pushed into a default property too, to extract all specific stuff from the app.py

**Comment by jlubken** [comment]
For some reason the regional population changed in the display:
- original : 4119405
- modified: 3491064

**Comment by jlubken** [comment]
The initial conditions regions list has changed orientation with an extra bullet.

**Comment by quinn-dougherty** [comment]
i was aware of that, sorry - `st.markdown` doesn't pick up on `\n`. Would it be better with no extra bullet, but keeping the changed orientation?

**Comment by jlubken** [comment]
I'm OK with that. It doesn't look quite as good, but this is the most custom part of the render.

**Comment by quinn-dougherty** [comment]
will close https://github.com/codeforphilly/chime/issues/110

**Review by jlubken — APPROVED** [review]

**Pull request merged**
