### PR TITLE
[Dash] content and style update

### PR DESCRIPTION
**Pull request by ecsmyth**
* Change navbar DropdownMenu to right aligned so menu doesn't render off screen
* Style navbar inner container as fluid to push content to sides
* Simplify header and adjust style to correct for alignment issues at various window sizes
* Remove intro content now available from navbar dropdown

### CODE REVIEW

**Comment by ecsmyth** [comment]
### At 2560x1440 resolution
image

### At 1024x768 resolution
image

**Comment by mishmosh** [comment]
Re bullet point 4, "can I use this for my region?" is a really common question so I think we should keep some of the intro text. What about editing it down to this? Social & contact links can still move to the dropdown.

> _This tool was developed by the [Predictive Healthcare team](http://predictivehealthcare.pennmedicine.org/) at [Penn Medicine](https://www.pennmedicine.org) to assist hospitals and public health officials with hospital capacity planning, but can be used anywhere in the world. Customize it for your region by modifying inputs in the left pane, or read the [User Documentation](https://code-for-philly.gitbook.io/chime/) to learn more._

**Comment by ecsmyth** [comment]
@mishmosh, good point. I've re-added the text and moved it from the `intro` to the `header` so that it will display more quickly and even if the model breaks.

image

**Review by ckoerber — APPROVED** [review]
Thanks again for the PR, @ecsmyth :) I tested locally, works as described and adding static text to the header instead of the dynamic intro sounds like a good idea.

*Side note*: Since this is the first time someone mentioned responsiveness, when hitting the sm bootstrap breakpoint, the content overlaps with the sidebar. But this might be better resolved in another PR; I'll file an issue.

**Pull request merged**
