### PR TITLE
#103, #105 value range checks & bounds

### PR DESCRIPTION
**Pull request by ckoerber**
Hello,

This PR contains updates for the app value range cross checks including equation checks. I tried to add sensible boundaries when possible.

This addresses #103 and #105.

Does this match expectations?

## Updates

In `apps.py`:
* Added min/max limits for sliders if sensible
* Updated computed quantities for extremal cases
* Allowed `detection_prob` to be unknown (None)

In `penn_chime/presentation.py`: 
* Allowed rendering of unknown detection rate

### CODE REVIEW

**Comment by quinn-dougherty** [comment]
This effects mathematical results so needs to be reviewed by @cjbayesian & @mdbecker

**Comment by cjbayesian** [comment]
I'm getting this pretty often when I change the inputs:
image

**Comment by quinn-dougherty** [comment]
@cjbayesian that's the cache at work. https://github.com/CodeForPhilly/chime/pull/97

**Comment by cjbayesian** [comment]
@quinn-dougherty So, the cache is making it worse?

**Review by cjbayesian — APPROVED** [review]
Manually confirmed the calculation changes are correct and line up with prod, value for value.

**Pull request merged**
