### PR TITLE
Refactor deployment workflows based on GitHub Releases

### PR DESCRIPTION
**Pull request by lottspot**
This change set heavily refactors the automated deployment workflow to circumvent challenges with using GitHub actions for CD and to more closely match the current development release process. The workflow implemented is as follows:

* When a [GitHub release is created](https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository#creating-a-release), build a container image from the release and publish the image to GitHub packages
  * The main implication here is that we are performing builds when a release is created, rather than when a new tag is pushed
* After image is published, edit the k8s/app.yaml manifest to deploy the new image version, add the manifest to a zip file, and publish the zip file to the Release
  * For prod releases, the app.yaml manifest will be packaged with the manifests in k8s.prod
  * For pre-releases, the app.yaml manifest will be packaged with the manifests in k8s.preprod
* Next step is dependent on wether the release is marked as a pre-release or a full release:
  * For pre-releases, download the manifest files published in step 2 and apply them to the preprod cluster
  * For full releases, download the manifeast files published in step 2, acquire a diff via `kubectl diff`, and open a PR from develop into releases/v1 containing the diff in the description
* FULL RELEASES ONLY: Once the PR is merged, download the manifest files which were published to the Release and apply them to the production cluster

This workflow will allow the development team to perform releases without any intervention from the ops unit. Working examples of workflow steps:

- [Published pre-release](https://github.com/lottspot/chime/releases/tag/v0.0.2-rc.1)
- [Pre-release workflow run](https://github.com/lottspot/chime/actions/runs/75570366)
- [Published full release](https://github.com/lottspot/chime/releases/tag/v0.0.2)
- [Full release workflow run](https://github.com/lottspot/chime/actions/runs/75578572)
- [PR opened by full release workflow](https://github.com/lottspot/chime/pull/30)
- [Deploy workflow from PR merge](https://github.com/lottspot/chime/actions/runs/75585024)

### CODE REVIEW

**Comment by lottspot** [comment]
Note on changes to tagging conventions:

This PR sets the repository tag to `:latest` for the chime container image. Each new **prod** release will be pushed with a `:latest` tag in addition to its version tag. This will allow the repo version to safely remain labeled `:latest`, while still revving the active tag version on the cluster with each deploy.

**Comment by themightychris** [comment]
@lottspot incredible work! The only thing that could make this better is [publishing deployment records](https://github.com/chrnorm/deployment-action) (you could use deployments and their events to mediate the workflow, but that might be more trouble than it's worth. I think just creating the records against the ref being deployed and updating its status throughout the workflow will give us deployment status in the PR GUI and a sep slack event)

Edit: this one might be more appropriate: https://github.com/unacast/actions-github-deployment-status

**Review by themightychris — APPROVED** [review]

**Comment by lottspot** [comment]
Deployments API integration has been added in f17c5d3. Working examples:

- [Preprod release & deployment](https://github.com/lottspot/chime/actions/runs/76622675)
- [Prod release](https://github.com/lottspot/chime/actions/runs/76624565)
- [Prod deployment](https://github.com/lottspot/chime/runs/581013845?check_suite_focus=true)

And the [resulting deployment objects](https://github.com/lottspot/chime/deployments)

**Comment by MooseQuest** [comment]
I reread this with a clearer mind -- One that I like is the fact we are building the github package, making it available to pull done. This is excellent indeed.

**Review by MooseQuest — APPROVED** [review]
🎉🤜🏼 Very well done. I added a comment below.

**Pull request merged**
