### PR TITLE
Adapt Parameters and CLI to mostly automatically stay in sync

### LINKED ISSUE #491: ["bug"] CLI is out of date relative to the web app implementations
### Description:

As features have been added to the web application front-ends in Streamlit and Dash, the CLI hasn't been kept in sync

### Expected behavior:

The CLI accepts all the same parameters as the web interface, and produces the same results

### What I got instead:

At least some parameters are missing

### Suggested fix:

Automatically generate the list of arguments to accept based on information in the `Parameters` class.

### PR DESCRIPTION
**Pull request by PhilMiller**
Rather than hard-coding the available parameters in the CLI source, have it read the relevant set out of Parameters directly.

Fixes: #491

### CODE REVIEW

**Comment by PhilMiller** [comment]
There's weirdness with the imports used by the CLI vs `pytest` and the web apps, which makes the CLI fail. I don't have the Python knowledge to resolve that, but this all works with that hacked around (non-relative imports of everything, everywhere)

**Comment by PhilMiller** [comment]
We may want to converge the web app code a little bit, to have the descriptive text for the parameters live in `parameters.py`, so that we're guaranteed that any changes to any UI are reflected in all of them.

**Comment by jlubken** [comment]
The cli should work with relative imports once the user installs the module `pip install .` The cli is not a script: `setup.py` adds an endpoint.

**Comment by jlubken** [comment]
I'm going to accept this and then open/start on another ticket to get the config file leaded and fix the cli relative imports.

**Review by jlubken — APPROVED** [review]

**Pull request merged**
