### PR TITLE
Create generic PR template

### PR DESCRIPTION
**Pull request by BrianThomasRoss**
:tada:

### CODE REVIEW

**Comment by ckoerber** [comment]
Regarding:

> - [ ] Runs without error or warning

I also check a lot that the web interface was tested. Not sure how to word this.

**Comment by BrianThomasRoss** [comment]
> Regarding:
> 
> > * [ ]  Runs without error or warning
> 
> I also check a lot that the web interface was tested. Not sure how to word this.

Could add:
- [ ] Does not create new issues or bugs 

If that sounds right?

**Review by rcknplyr — COMMENTED** [review]
Hi @BrianThomasRoss ,
Sorry I'm not entirely sure I'm understanding how this is intended to work. Is the intent to have the creator of every PR check each of these 6 boxes before initiating a PR? If so, that might add a lot of friction. Would it make sense to also offer a 'check all' option so they can  do this with 1 click? Let me know if I'm misinterpreting this one.

**Comment by BrianThomasRoss** [comment]
> Hi @BrianThomasRoss ,
> Sorry I'm not entirely sure I'm understanding how this is intended to work. Is the intent to have the creator of every PR check each of these 6 boxes before initiating a PR? If so, that might add a lot of friction. Would it make sense to also offer a 'check all' option so they can do this with 1 click? Let me know if I'm misinterpreting this one.

This was more intended as a tool for the reviewer

**Review by ckoerber — APPROVED** [review]

**Pull request merged**
