### PR TITLE
Fix cli execution

### LINKED ISSUE #198: cli.py fails to run
I see at least an import error and attempted division of `NoneType / NoneType`

### PR DESCRIPTION
**Pull request by PhilMiller**
Fixes: #198

### CODE REVIEW

**Comment by PhilMiller** [comment]
More fixes coming - code had apparently bit-rotted

**Review by quinn-dougherty — APPROVED** [review]

**Comment by quinn-dougherty** [comment]
this makes basic sense and it's small so i'm gonna trust you on it--- I'll ping Jason on slack about developign some CLI tests.

**Comment by PhilMiller** [comment]
Thanks. I was actually using it to test my work on #187, so I can at least confirm that it no longer crashes, and outputs about what I expect now.

**Comment by chrowe** [comment]
I am able to run `python cli.py --file ./settings.cfg` as of 03753c62a00b3394500dd9f08c8c85a74ba0dd91

Is this something that would have broken since then?

**Pull request merged**
