### PR TITLE
[dash] Add linebreaks to sidebar

### PR DESCRIPTION
**Pull request by kmid5280**
Contributes to issue #315. Defined and added line breaks to sidebar with style included. Changed margins on header style to better accommodate new line break.

### CODE REVIEW

**Comment by quinn-dougherty** [comment]
Screenshot from 2020-04-02 10-06-21
this is what i'm getting in the chart when i check it out locally.

**Comment by quinn-dougherty** [comment]
here's the error message 

```
2020-04-02 10:06:06,651 - chime_dash.app.run - ERROR - Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/home/quinn/.local/share/virtualenvs/chime-zS2_QXL9/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/quinn/.local/share/virtualenvs/chime-zS2_QXL9/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/quinn/.local/share/virtualenvs/chime-zS2_QXL9/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/quinn/.local/share/virtualenvs/chime-zS2_QXL9/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/quinn/.local/share/virtualenvs/chime-zS2_QXL9/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/quinn/.local/share/virtualenvs/chime-zS2_QXL9/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/quinn/.local/share/virtualenvs/chime-zS2_QXL9/lib/python3.7/site-packages/dash/dash.py", line 1461, in dispatch
    response.set_data(self.callback_map[output]["callback"](*args))
  File "/home/quinn/.local/share/virtualenvs/chime-zS2_QXL9/lib/python3.7/site-packages/dash/dash.py", line 1341, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/home/quinn/Projects/misc/COVID/chime/src/chime_dash/app/utils/callbacks.py", line 36, in callback_wrapper
    return self.callback_fn(*args, **kwargs)
  File "/home/quinn/Projects/misc/COVID/chime/src/chime_dash/app/pages/sidebar.py", line 145, in update_parameters
    inputs_dict = Sidebar.get_formated_values(input_values)
  File "/home/quinn/Projects/misc/COVID/chime/src/chime_dash/app/pages/sidebar.py", line 136, in get_formated_values
    result[key] = datetime.strptime(value, "%Y-%m-%d").date() if value else value
TypeError: strptime() argument 1 must be str, not int
```

**Comment by kmid5280** [comment]
@quinn-dougherty Thanks. See how it is now.

**Comment by quinn-dougherty** [comment]
hi @kmid5280 could you please reopen this PR against the `develop` branch?

**Comment by ckoerber** [comment]
Hello @kmid5280,

Thank you for helping out. I have to admit that quite a bit has changed since you have created the fork. I took the freedom to open a [PR against your fork](https://github.com/kmid5280/chime/pull/1) which resolves the merge conflict (and tested it on my end). Can you please make sure that I did not break something unintentionally. Otherwise, the PR addresses the issue as expected and can be merged in once the conflict is resolved.

**Review by ckoerber — APPROVED** [review]
Line breaks are in place and the branch is up to date with develop. Thanks @kmid5280!

**Review by BrianThomasRoss — APPROVED** [review]

**Pull request merged**
