### PR TITLE
Move computation

### LINKED ISSUE #108: Replace use of multiple vectors with dataframes
@jlubken added description here. Feel free to change

Use sim_isr_df instead of sim_sir.
Replace vector dispositions with a dataframe.
Simplify chart builders since the columns are known.

### LINKED ISSUE #195: Fix incorrect vectors and cli
I suspect that these vectors are incorrect and hopefully unused:
- parameters.hospitalized_v
- parameters.icu_v 
- parameters.ventilated_v

Fix cli.

### PR DESCRIPTION
**Pull request by jlubken**
Move all computation into models.py SimSirModel.

Most properties of Parameters have moved to the SimSirModel.

Replace vectors with raw df from sim_sir_df.

Use column names from sim_sir_df.

Use column names from dispositions dictionary in a way that allows dispositions to be extended beyond 'hospitalized', 'icu', 'ventilated' in model.

Closes #195  Closes #108

### CODE REVIEW

**Comment by quinn-dougherty** [comment]
closes https://github.com/CodeForPhilly/chime/issues/108 ?

**Comment by jlubken** [comment]
Yes except for the dispositions dict. Close 108 if you want.

**Review by quinn-dougherty — APPROVED** [review]
tested locally and read all the code -- all good from my end

**Comment by mariekers** [comment]
does this fix #211 ?

**Comment by quinn-dougherty** [comment]
> does this fix #211 ?

no

**Pull request merged**
