### PR TITLE
Merge penn fix conflicts

### PR DESCRIPTION
**Pull request by sam-qordoba**
This is just #49 but with 2 commits of mine fixing the merge conflict.

Some notes I am copying from that PR:

This should be merged before #50 or #51 or I worry they will get overwritten.

A lot of these changes are things like adding definitions, and using `Length of Stay` instead of `LOS`, as requested by a non-native English speaker working on translating this. However, there is also the change to the denominator of `beta`, which now includes `* (1-relative_contact_rate)`, which propagates through numbers that feed the charts. So this also affects the analysis.

### CODE REVIEW

**Comment by mdbecker** [comment]
hey @sam-qordoba I'm seeing several regressions against the current prod app. I'll start a list of them here:
Prod:
image
Branch:
image

Prod:
image
Branch:
image

Prod:
image
Branch:
image

I'll add more as I find them

**Comment by cjbayesian** [comment]
A key difference between this and current prod is the user input of prob of detection, rather than inferring it directly from number of hospitalizations, hospitalization %, and market share.

**Comment by quinn-dougherty** [comment]
I think the discrepency w the data/results are because of `The estimated number of currently infected individuals is 1260.` (this branch) vs. `The estimated number of currently infected individuals is 533.` (prod). other than that the calculation might not be off? 

i'm currently fixing the input order in the sidebar. 

@cjbayesian probability of detection isn't in prod, so where should i put that on the sidebar (between what 2 parameters)? or should i bake in a default and remove it from UI? if there's an earlier version where that parameter was inferred, could you point me to that strip of code so i can restore it?

**Comment by cjbayesian** [comment]
@quinn-dougherty Thanks. It's https://github.com/pennsignals/chime/blob/f4eb1a5e3e25af105dc76e32e099eedad887f307/app.py#L62 and https://github.com/pennsignals/chime/blob/f4eb1a5e3e25af105dc76e32e099eedad887f307/app.py#L63

There the `detection_prob` and `total_infections` are being inferred based on `current_hosp`, `Penn_market_share`, `hosp_rate`, and `initial_infections`.

**Comment by cjbayesian** [comment]
So we should remove the probability of detection input from the sidebar. All of the description text is in line with this method of calculating the total number of currently affected individuals.

We can consider changing the way this is being estimated in a future version, but would need to ensure that all description text, documentation, explanations are consistent with the approach.

**Comment by cjbayesian** [comment]
Side-by-side now looks good to me. @mdbecker to confirm.

**Comment by mdbecker** [comment]
Checking now. Thanks!

**Pull request merged**
