### PR TITLE
Implement streamlit caching

### PR DESCRIPTION
**Pull request by nickcanz**
This PR adds caching to model functions with the goal of caching the outputs to reduce page load/resources needed.

/cc https://github.com/CodeForPhilly/chime/issues/14

### CODE REVIEW

**Comment by mariekers** [comment]
I think Quinn & Sam can talk more about streamlit caching (and whether this breaks anything)

**Comment by quinn-dougherty** [comment]
hi thanks for knocking this out. code looks good but when i checkout and run it locally the headers are all messed up 
Screenshot from 2020-03-19 14-51-00
Any idea why that might be? does it look the same on your end? i'm trying things w my browser to see what's up

**Comment by nickcanz** [comment]
@quinn-dougherty I don't see that locally! I'm using Chrome on OSX and running `./script/server`. Which are you using?


Screen Shot 2020-03-19 at 15 06 32
Screen Shot 2020-03-19 at 15 06 42

**Comment by quinn-dougherty** [comment]
ok i'm using `docker-compose up`, (and firefox), one of those are probably the issue. 

the performance of the app is solid -- caching is doing exactly what it set out to do. so i'm approving.

**Review by quinn-dougherty — APPROVED** [review]
thanks

**Comment by quinn-dougherty** [comment]
sorry this got caught up in a bustle today-- the penn folks were debugging prod but we thought in slack they were talking about this branch. this is ready tho

**Pull request merged**
