### PR TITLE
Fix parameters and "constants"

### LINKED ISSUE #466: ["dash"] Singleton and DEFAULTS
### Description:

DEFAULTS is not a constant, it must be loaded per client session. Be careful when using module constant or singleton that would cause defaults to be initialized only when a container reloads.

Review all code for DEFAULTS. Replace references to DEFAULTS with values form query parameters, or data updated by the user through the sidebar controls.

[ ] This is something we can copy over from streamlit (screenshots if applicable)

### LINKED ISSUE #497: ["model"] Load parameters for the app from a file
Broken parameters. The cli, streamlit, and dash need to use a file for defaults. Ideally the file may optionally be specified through ENV, so that it works with Git Doc synchronization need for the upcoming PPE. Consolidate this into parameters.py. Allow data science to update the file.

### PR DESCRIPTION
**Pull request by jlubken**
Defaults must come from a file and be removed from the code entirely, or we will keep getting breakage between the cli, streamlit and dash. No fallback values except for explicit checks for None -> today() for current_date and mitigation_date, and these checks are embedded in the class.

Pass the parsed default Parameters through to components.

Add PARAMETERS env variable to locate the appropriate parameters cfg file.

The cli needs date_first_hospitalized xor doubling_time.
The webapps need both date_first_hospitalized and doubling_time. One is overridden in the ui.
Separate cypress config, so that tests don't break even when the values for the webapps or the cli are updated.

Closes #497 Closes #466

### CODE REVIEW

**Review by quinn-dougherty — DISMISSED** [review]
makes sense to me, let me test it locally real quick

**Comment by quinn-dougherty** [comment]
i think you also Closes https://github.com/codeforphilly/chime/issues/172

**Comment by quinn-dougherty** [comment]
@jlubken i'm getting this immediately upon running either streamlit or dash

```File "/home/quinn/.local/share/virtualenvs/chime-zS2_QXL9/lib/python3.7/site-packages/streamlit/ScriptRunner.py", line 322, in _run_script
    exec(code, module.__dict__)
File "/home/quinn/Projects/misc/COVID/chime/src/app.py", line 31, in <module>
    d = Parameters.create(os.environ, [])
File "src/penn_chime/parameters.py", line 342, in create
    Positive(key='hospitalized_days', value=a.hospitalized_days)
File "src/penn_chime/validators/base.py", line 10, in __call__
    self.validate(key, value)
File "src/penn_chime/validators/validators.py", line 38, in validate
    raise ValueError(f"{key} is required.")```

am i missing something?

**Comment by quinn-dougherty** [comment]
```^C^C(chime) 11:47:51:chime:$> python src/dash_app.py 
Traceback (most recent call last):
  File "src/dash_app.py", line 9, in <module>
    ENV, DASH = create_app(context="prod")
  File "/home/quinn/Projects/misc/COVID/chime/src/chime_dash/__init__.py", line 39, in create_app
    Parameters.create(os.environ, []),
  File "/home/quinn/Projects/misc/COVID/chime/src/penn_chime/parameters.py", line 342, in create
    Positive(key='hospitalized_days', value=a.hospitalized_days)
  File "/home/quinn/Projects/misc/COVID/chime/src/penn_chime/validators/base.py", line 10, in __call__
    self.validate(key, value)
  File "/home/quinn/Projects/misc/COVID/chime/src/penn_chime/validators/validators.py", line 38, in validate
    raise ValueError(f"{key} is required.")
ValueError: hospitalized_days is required.
```

**Comment by BrianThomasRoss** [comment]
Seems to be just a little issue here where the defaults directory needs to be moved, container build fails due to FileNotFound.

499-bug

**Comment by BrianThomasRoss** [comment]
I've got it working now

[test-heroku](https://btr-test.herokuapp.com/#population=30000000&market_share=15&current_hospitalized=70&date_first_hospitalized=2020-03-07&doubling_time=4&relative_contact_rate=30&hospitalized_rate=2.5&icu_rate=0.75&ventilated_rate=0.5&infectious_days=14&hospitalized_los=7&icu_los=9&ventilated_los=10&n_days=100&current_date=2020-04-07&max_y_axis_value=None&show_tables=True)

**Review by BrianThomasRoss — APPROVED** [review]
Looks like a good step in the right direction.

**Comment by quinn-dougherty** [comment]
The reason for my previous error was that i forgot to run `PARAMETERS=defaults/webapp.cfg`, which it said to do in the docs. disregard.

**Pull request merged**
