### PR TITLE
[Dash] layout update and refactor

### PR DESCRIPTION
**Pull request by ecsmyth**
image

### `./src/chime_dash/app/components`
* `navbar.py` Change navbar to fixed position at top of window. Fix nested anchor elements. Move Penn Medicine logo and link from header to navbar
* `container.py` Create component that wraps sidebar and content. Add children callback inputs/outputs to own, call child callbacks, re-calculate (temporarily?) model
* `__init__.py` refactor out container class that holds sidebar and main content. Remove model re-calculation code
* `content.py` Create component that wraps all of the model presentation. Add children callback inputs/outputs to own, call child callbacks
* `sidebar.py` Style to be fixed position. Fix lint issues
* `header.py` Remove Penn Medicine anchor w/ logo moved to navbar
 
### `./src/chime_dash/app/templates/en`
* `header.yml` remove `logo-title` and `logo-text` moved to navbar

### Possible todo before merge:
* Generalize `__init__.py`, `content.py`, and `container.py` into container class.
* Move model re-calculation logic out of `container.py` callback function into ?

### CODE REVIEW

**Review by BrianThomasRoss — APPROVED** [review]

**Comment by quinn-dougherty** [comment]
>Possible todo before merge: Generalize __init__.py, content.py, and container.py into container class.

this should be it's own PR.

**Comment by quinn-dougherty** [comment]
>Possible todo before merge:  Move model re-calculation logic out of container.py callback function into ?

i'm honestly ready to merge it now

**Comment by quinn-dougherty** [comment]
Screenshot from 2020-03-28 09-16-44

i'm not getting penn logo loaded. i disabled ublock origin

**Comment by ecsmyth** [comment]
@quinn-dougherty, ack. I can create new issues for the two todos once this PR is resolved.

**Comment by ecsmyth** [comment]
I'm a little worried about the performance and maintainability of the current callback approach of using a single decorator on the body instance. AIUI every callback function is called every single time, and it's easy to create a nested element that is disconnected from the callback tree.

**Comment by ecsmyth** [comment]
@quinn-dougherty, what browser? Any console errors? wfm in Chromium and Firefox Nightly.

Generally, we might want an issue similar to #118 for other assets (E.g., Penn logos, Bootstrap css). First-party hosting has some issues but should alleviate risk of issues from 3rd party servers being down, ad blockers blocking the requests, etc.

**Review by ckoerber — APPROVED** [review]
@ecsmyth Thanks for the edits and updates. I have locally tested the PR and I could not find any unintended features :) and I believe the `container` refactor for the `sidebar` and `content` clears things up.

I also like the idea of adding the attribute `components = OrderedDict(...)`. I believe it would be helpful to place this in the `base.Component` class. In principle, it would allow us to automatically propagate callback arguments, but I also do agree that performance might be sacrificed doing so (see below). As I agree with @BrianThomasRoss that the `base.Component` class seems to be a utility class, we should update the attribute and move it to another location in future PR.

Regarding callback performance. Yes, currently all form changes cause one global callback and thus there is redundancy. In principle, it is not needed to recompute all values if one just expands the table collapse div for example. The reason it is one callback was that it was easier (as well to implement as for others to follow up on--which is important so people not familiar with dash could also contribute). E.g., we could just loop over children callback arguments and don't break the logic. Having separate callbacks should be doable as well, but might require knowledge about subcomponents--like this part is connected to a computation layer but that part is a pure visibility layer which stands on its own. I don't have preferences about which choice might be better. Even better, if you have an idea of how to introduce several callbacks without sacrificing the modular structure, please let us know.

Tiny note: my linter is complaining about the order of imports and unused imports (likely a few of them are my fault). I believe @BrianThomasRoss is currently working on that as well (so let's ignore that for now).

**Pull request merged**
