### PR TITLE
[dash] PDF printing from application

### PR DESCRIPTION
**Pull request by Zedmor**
Allows PDF printing for application through Selenium driver and creating subapp.

captured (1)

Need chrome webriver - dependency installed - not familiar with Heroku - is it possible?

### CODE REVIEW

**Comment by quinn-dougherty** [comment]
```(chime) 08:58:01:chime:$> python src/dash_app.py 
Traceback (most recent call last):
  File "src/dash_app.py", line 33, in <module>
    os.makedirs(UPLOAD_DIRECTORY)
  File "/home/quinn/.local/share/virtualenvs/chime-zS2_QXL9/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/quinn/.local/share/virtualenvs/chime-zS2_QXL9/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/app'
```

@Zedmor are you familiar with this message? is there a quick fix?

**Comment by quinn-dougherty** [comment]
also heads up i updated `requirements.txt` for your dependencies.

**Comment by Zedmor** [comment]
> ```
> Traceback (most recent call last):
>   File "src/dash_app.py", line 33, in <module>
>     os.makedirs(UPLOAD_DIRECTORY)
>   File "/home/quinn/.local/share/virtualenvs/chime-zS2_QXL9/lib/python3.7/os.py", line 211, in makedirs
>     makedirs(head, exist_ok=exist_ok)
>   File "/home/quinn/.local/share/virtualenvs/chime-zS2_QXL9/lib/python3.7/os.py", line 221, in makedirs
>     mkdir(name, mode)
> PermissionError: [Errno 13] Permission denied: '/app'
> ```
> 
> @Zedmor are you familiar with this message? is there a quick fix?

Well I guess flask do not have access to /app... 
if you develop locally then probably just chown /app to your user and we probably will need to define this through Env var anyway.

**Comment by Zedmor** [comment]
Rebased on top to latest changes to maintain mergability

**Comment by ckoerber** [comment]
Ok, the branch [251_add_pdf_export_bufferd](https://github.com/CodeForPhilly/chime/tree/251_add_pdf_export_bufferd) now contains an update which creates a buffered file and thus does not need static or media directories. Please take a look if this is deployable. 

It is still work in progress as the graphs are currently not rendered and some functions should be moved to other places. I have also [filed a PR on your repo](https://github.com/Zedmor/chime/pull/3) @Zedmor, in case this works out.

It utilizes URL parameters and is thus related to #146. If we follow up in this direction, we should combine efforts.

**Comment by BrianThomasRoss** [comment]
Will reopen this at a later time

**Pull request closed without merging**
