### PR TITLE
#560 Limit forecasting window to one month

### LINKED ISSUE #560: Limit forecasting window to one month
User should only be able to forecast curve for the next 4 weeks

- [ ] "number of days to project" min is 1, max is 30
- [ ] update documentation to explain why and how the model should be used

### PR DESCRIPTION
**Pull request by mangalap123**
Limit forecasting window to one month #560
Setting "number of days to project" min is 1, max is 30

# Link to issue

- Fixes #560

# Changelog entry

- Short description of problem & solution (1-3 sentences, depending on scope of change)
Setting the Min(1) and Max(30) numbers for "number of days to project" parameter

# Additional info

- Anything else reviewers and future readers should know

---

### <center>For Reviewer</center>

- [ ] Submitted under the correct tag
- [x] Runs without error or warning
- [x] Documentation  revised / included
- [x] Unit tests included
- [x] Issues referenced
- [x] Does not create new bugs / issues

### CODE REVIEW

**Review by BrianThomasRoss — DISMISSED** [review]
When I  ran locally the lower bound was 30 days and  seemed no upper bound
image

**Review by BrianThomasRoss — APPROVED** [review]
Works great on my end thanks again for the contribution

**Comment by DougManuel** [comment]
I couldn't find the reason for this change. It will be difficult for us and I expect others who use the app for longer range counterfactual examples of the effectiveness of social distancing.

**Comment by BrianThomasRoss** [comment]
> I couldn't find the reason for this change. It will be difficult for us and I expect others who use the app for longer range counterfactual examples of the effectiveness of social distancing.

Hi there, @DougManuel so I would encourage you to check out [the repository here.](https://github.com/pennsignals/chime_sims)

My basic understanding, and I'd welcome correction by members of the Penn team if I'm handing out bad information, is that currently they have parameters being utilized by the model that essentially represent a single snapshot in time. Using that snapshot a forecast is then generated by using those limited points to outline generally course that could be expected from the "snapshot". So I think of this like trying to do facial recognition with a very low quality video camera.

The model at the repo linked above makes tremendous strides in improving the accuracy and utility of the forecasts.

- It can accepts as input 2 matrices one consisting of the recorded census data similar to the output of this model, as well as another container more refined approaches to things like calculating reduction in relative contact rate, rates of specific interventions, and LOS data and some hyperparameters to allow for finer tuning.

- It incorporates Bayesian inferencing techniques to update the model as it moves through the timeline which produces a perhaps more accurate reflection of reality but also generates distributions of predictions which could allow for answering questions like "Whats my best case worst case here?"

**Comment by DougManuel** [comment]
Thanks for the explanation. 
From a user's perspective, what has been helpful from this repo's model has been for us has been:
- accessible - web-based
- initiated on hospital census
- includes social distancing. 

The effect of social distancing dwarfs all other parameters outside the R0, etc. There are many models available that focus on various improvements, but all models come to the same conclusion about the role of social distancing.

**Pull request merged**
