### PR TITLE
Adding env variables to use for google api

### LINKED ISSUE #500: Deploy Google API Secrets to k8s
# Background/Details

In order to satisfy #454 we must create secrets in the k8s infrastructure to be consumed as ENVIRONMENT_VARIABLES in the container. 

Once the app is deployed, it will look for secrets based on ENVIRONMENT_VARIABLES in the pod (app environment) that it is running.

Secrets are the be prepended with `GAPI_CRED_<cred_key_field>` with the `value` entered in as a secret.

## Example
Example from client_secret.json:
`{
  "type": "service_account"
}`

Environment Variable

`GAPI_CRED_TYPE`

Secret

`service_account`

Called in app:

`{
  "type": "$GAPI_CRED_TYPE"
}`

### PR DESCRIPTION
**Pull request by MooseQuest**
This closes #500

The secrets file associated with this is deployed into bit warden. Need a chime-ops admin to retrieve. Environment variables are called within the app itself.

### CODE REVIEW

**Comment by lottspot** [comment]
If we apply this to prod before the secrets are added, it's gonna break deployments. We should probably hold this merge until the secrets are created.

**Comment by MooseQuest** [comment]
I created the secrets in preprod — I’ll create the in prod after testing.

**Comment by MooseQuest** [comment]
@lottspot The secrets were created at the time of this PR merged. I'm still a bit confused on how to rudimentary test this change with the branches, so it's just a matter of testing with...? (Code has to be updated in the app, and I could be mistaken but we don't build the container from the build process).

**Comment by MooseQuest** [comment]
> @lottspot The secrets were created at the time of this PR merged. I'm still a bit confused on how to rudimentary test this change with the branches, so it's just a matter of testing with...? (Code has to be updated in the app, and I could be mistaken but we don't build the container from the build process).

I see this: https://github.com/CodeForPhilly/chime/blob/dsgit1-patch-1/.github/workflows/dockerpublish.yml

But I think what I'm missing is does this actually update preprod (in the PR? or does it do it after the PR is approved)

**Comment by lottspot** [comment]
> But I think what I'm missing is does this actually update preprod (in the PR? or does it do it after the PR is approved)

It does neither. It operates completely independent of PRs. It will deploy *tagged* versions to preprod, because only tagged versions are being built into docker images (merges into develop are not currently triggering docker builds).

**Comment by lottspot** [comment]
The way you would test this now that the secret is added to preprod would be to attempt to deploy this change to preprod, and confirm the rollout completes successfully. So, using preprod kubeconfig:

```
kubectl apply -f k8s/app.yaml
kubectl -n chime rollout status deployment.v1.apps/chime
```

just... be sure you aren't using the wrong kubeconfig 😉

**Comment by lottspot** [comment]
The version of the code doesn't really matter as far as testing this change from an infrastructure perspective. You can simply run the test from this branch.

**Comment by MooseQuest** [comment]
The secrets have been applied to both environments. We can unblock this PR.

**Comment by lottspot** [comment]
The changes to app.yaml should be applied to/verified in preprod before we unblock/merge

**Comment by MooseQuest** [comment]
> kubectl apply -f k8s/app.yaml
> kubectl -n chime rollout status deployment.v1.apps/chime

This is complete:

Screen Shot 2020-04-08 at 17 07 13

```
17:06:50 khende810 HQSML-1717855 /Users/khende810/repo/chime google-api-sheets
$ kubectl -n chime rollout status deployment.v1.apps/chime
deployment "chime" successfully rolled out
```

**Review by lottspot — APPROVED** [review]
Looks good!

**Comment by rcknplyr** [comment]
@lottspot looking to close down open issues/PRs on this repo. Do we need to implement this in this repo, given we are moving to maintenance mode?

**Pull request merged**
