### PR TITLE
Add timeout wait to Cypress

### LINKED ISSUE #214: Cypress intermittently times out
Reported through slack - sometimes this step fails, but will pass on re-execution

e.g. https://github.com/CodeForPhilly/chime/pull/191/checks?check_run_id=528505109

### PR DESCRIPTION
**Pull request by MooseQuest**
This should tell Cypress to wait for the app to come up before timing out (300) -- This fixes #214

### CODE REVIEW

**Comment by MooseQuest** [comment]
https://github.com/CodeForPhilly/chime/actions/runs/66731346 for your review.

**Comment by MooseQuest** [comment]
These configurations were obtained from: https://github.com/cypress-io/github-action/pull/43/commits/12c5844257eba301ca7dbf77652022741e96a90a

**Review by themightychris — APPROVED** [review]

**Comment by themightychris** [comment]
@MooseQuest this is a good start, going to merge in as-is for now. Let's see how this impacts things, but I think it may _also_ be helpful to have a wait command prefixing the first test, as this wait-for command may delay tests starting until the HTTP server starts responding to `GET /` but with this app i've noticed there are a few async elements within the client side that take an extra few moments to establish connections and come online on first load

**Comment by MooseQuest** [comment]
Understood. I don't think it's the HTTP server that's not responding, I think the app is not up yet. This we saw in prod waiting for websockets to come up. Let's see how this works out.

**Pull request merged**
