### PR TITLE
Improve test coverage (dash tests)

### PR DESCRIPTION
**Pull request by Zedmor**
This is another effort to merge those changes (we will fix CI first)

### CODE REVIEW

**Comment by grahamalama** [comment]
@Zedmor I recently submitted https://github.com/CodeForPhilly/chime/pull/389 that started a `conftest.py`. You can probably integrate the changes you added in `tests/dash_app/conftest.py` to ` tests/conftest.py`

**Comment by pjhoberman** [comment]
What's the fix (maybe there's documentation?) to fix this error for each developer?

`selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH.`

**Comment by jlubken** [comment]
We're going to go with cypress and github actions on this one.

**Comment by BrianThomasRoss** [comment]
Temporarily closing

**Pull request closed without merging**
