### PR TITLE
[dash] Remove Penn hospital references from main page

### PR DESCRIPTION
**Pull request by kmid5280**
Issue #316 Removed Penn hospital references from Projected Admissions and Projected Census graphs. It may be possible to go further and allow the user to specify the hospital, but that might only be worth it if doing so would yield different data.

### CODE REVIEW

**Comment by kmid5280** [comment]
I'm not sure why all these other commits were included in this PR. There was only one change I wanted to push.

**Comment by ckoerber** [comment]
Though the proposed changes are also applicable to the dash app, the corresponding file for the dash branch is not yet changed (`templates/en/visualizations.yml`). I am not sure if this belongs to the dash branch @quinn-dougherty.

**Comment by quinn-dougherty** [comment]
@kmid5280  i feel like you branched off of develop, not off of dash. that's what it seems like anyway. i wonder if we could figure out the git fu to rebase https://github.com/CodeForPhilly/chime/pull/323/commits/b668ff35a51b0e788c0d9fb372e4f9aac6b28b60 to dash branch.

**Comment by kmid5280** [comment]
@quinn-dougherty I think I made some mistakes on this one. How would it be if I close the PR and try again?

**Pull request closed without merging**
