### PR TITLE
[WIP do not merge] refactor: draft component for running model without ui

### PR DESCRIPTION
**Pull request by machow**
This PR (cc @quinn-dougherty ) refactors out some of the dashboard logic into classes. This aims to allow...

* users to run models and generate outputs without the app
* developers to use alternative dashboards, by separating the UI layer from model logic

Note: if many inputs / intermediate calculations for plots overlap, then it makes sense to include them in the same class or put some of the intermediate calcs into the same place.

Progress, charts encapsulated in a class:

- [x] new_admissions_chart
- [ ] TODO: add other chart funcs here

### CODE REVIEW

**Comment by machow** [comment]
I don't have a lot of time, but wanted to quickly put down an attempt at thinking through the existing architecture right now, and then move to  better place!

**Summary of key user issues:**

* **streamlit coupling:** users sometimes can't get a useful output without running the dashboard. This is important also for unit testing (eg mostly smoke testing in #115).
* **hard to understand end-to-end inputs to outputs:** two files (models and presentation) split logic up based on output, but the dashboard holds everything for what I would call "components", how inputs and functions combine to produce interesting outputs (sequence diagram below).

This sequence diagram illustrates the current flow of the app.

[](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gIGFwcC5weSAtPj5JbnB1dFdpZGdldDogZ2V0IHZhbHVlXG4gIGFwcC5weS0-Pm1vZGVsOiBnZXRfaG9zcGl0YWxpemF0aW9ucyh3aWRnZXRfc3RhdGUsLi4uKVxuICBhbHQgZG9jdW1lbnRcblx0ICBhcHAucHktPj5wcmVzZW50OiBkaXNwbGF5X2hlYWRlciguLi4pXG4gICAgcHJlc2VudC0-PnByZXNlbnQ6IHN0aW5nIHByb2Nlc3NpbmdcbiAgICBwcmVzZW50LT4-c3RyZWFtbGl0OiBzdC5tYXJrZG93bigpXG4gIGVsc2VcbiAgICBhcHAucHktPj5wcmVzZW50OiBkcmF3X3NvbWV0aGluZyhtb2RlbCBvdXRwdXQpXG4gICAgcHJlc2VudC0-PnByZXNlbnQ6IGFsdGFpciBhbmQgcGFuZGFzIGxvZ2ljXG4gICAgcHJlc2VudC0-PnN0cmVhbWxpdDogc3Qud3JpdGUoKSBcbiAgZW5kXG4gICIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

Note that this requires 3 behaviors be done through the dashboard:

* getting the initial parameters (they are in some cases hard-coded in the widgets)
* the dashboard calling the right functions from model, then passing their results to the right function in presentation to get e.g. a plot back.
* some of the functions are coupled with streamlit, so you can only get the desired result back through the dashboard (harder to test, can't be used outside dashboard):
  - `additional_projections_chart` returns an altair plot, but `show_additional_projections` executes `st.write` over a chart.

Here is an the flow the PR implements: 

[](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gIHNjcmlwdC0-PitFc3ROZXdBZG1pc3Npb25zOiBpbml0KCoqZGVmYXVsdF9wYXJzKVxuICBzY3JpcHQtPj4rRXN0TmV3QWRtaXNzaW9uczogcGxvdF9uZXdfYWRtaXNzaW9ucygpXG4gIEVzdE5ld0FkbWlzc2lvbnMtPj5tb2RlbDogZ2V0X2hvc3BpdGFsaXphdGlvbnMod2lkZ2V0X3N0YXRlLC4uLilcbiAgXG4gIEVzdE5ld0FkbWlzc2lvbnMtPj5wcmVzZW50OiBuZXdfYWRtaXNzaW9uc19jaGFydChtb2RlbCBvdXRwdXQpIFxuICBFc3ROZXdBZG1pc3Npb25zLS0-Pi1zY3JpcHQ6IGFsdGFpciBwbG90XG4gICIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9)

Note that...

* it can be called by a script or a dashboard
* it ties together the process of going parameters to an output

I'm not sure how important it is to have 1 class for each output, etc.. it seems largely a question of how much shared processing goes on to produce different outputs.

**Comment by quinn-dougherty** [comment]
i'm agnostic about `class`, i think the right chain of `def`s could get the same thing done. 

but to use classes as an example, the major thing i want to see here is 
- `build_admissions_df` and `new_admissions_chart` as a method of `EstimateNewAdmissions`
- lines 45-64 factored into a function `*args -> DataFrame`, and make it a method of EstimateNewAdmissions.

**Comment by machow** [comment]
Yeah that makes sense--someone more keyed is better to judge whether going from end-to-end is better in a function or class. Having those methods (or them as functions if avoiding classes) makes sense. I think the biggest value of either approach is just getting it out of the dashboard, so the CHIME crew can get that sweet intermediate-result-unit-test peace of mind :p

**Comment by quinn-dougherty** [comment]
i'm vetoing `dataclasses` in case someone wants to run it on 3.5 or 3.6. (dataclasses is strictly 3.7+) :/

**Comment by quinn-dougherty** [comment]
I'm closing this -- the ideas here helped us reconceptualize the architecture, and it's served its purpose. Thanks machow!

**Pull request closed without merging**
