### PR TITLE
#353 Adds Log Scale Checkbox in Sidebar

### LINKED ISSUE #353: [dash] Add log scale checkbox in sidebar
Put it at the bottom of the sidebar. When checked switch the y-axis scale to log scale. Equivalent to [`altair.ScaleType`](https://altair-viz.github.io/user_guide/generated/core/altair.ScaleType.html#altair.ScaleType)`== 'log'`

### PR DESCRIPTION
**Pull request by psahgal**
# Link to issue

- Fixes #353 

# Changelog entry

- Added a checkbox in the sidebar to toggle between log scale and linear scale on all charts.
- Updated chart creation code to toggle between log scale and linear scale. Some adjustments to the input data to the chart were needed, because a y value of zero on the chart when using log scale causes it to glitch horribly.
- Updated parameters so that `--use-log-scale` can be passed in from the command line. 

# Additional info

- I noticed some missing and unclear documentation, so I added doc tags where appropriate. I'm sorry if this made the pull request bigger than expected. Just trying to keep things tidy!

---

### <center>For Reviewer</center>

- [X] Submitted under the correct tag
- [ ] Runs without error or warning
   - There are still JavaScript warnings in the console, but they appear to be happening on the develop branch as well. Should I be worried?
- [ ] Documentation  revised / included
   - Does anyone know how I would update the user documentation?
- [X] Unit tests included
- [X] Issues referenced
- [X] Does not create new bugs / issues

### CODE REVIEW

**Review by BrianThomasRoss — CHANGES_REQUESTED** [review]
Really solid work, and love the thoroughness and attention to detail. So I'd really just like to see this split into the three areas I'm seeing here:

- 353 solution
- Improvement to the parser method in Parameters
- Documentation (many thanks)

solid work again though very very helpful

**Comment by psahgal** [comment]
@BrianThomasRoss sure, I can split it up! A couple questions:

- Should I make all new pull requests OR just update this one with just the fix and submit a few more pull requests?
- I'm not sure how to split out the solution for 353 and the parser updates...it seems like the sidebar settings and the command-line parameters are pretty tightly coupled together. Any tips...? If you see any chunks of code around parameter parsing that I can safely move out to another pull request, please let me know!

**Review by BrianThomasRoss — APPROVED** [review]

**Comment by BrianThomasRoss** [comment]
Honestly this is a solid contribution I don't see any reason to be a blocker here.

**Comment by psahgal** [comment]
Is there anything else I need to do here to get this merged?

**Comment by BrianThomasRoss** [comment]
I am testing deployment right now with this - there was a bug with the heroku deployment being broken so I was avoiding merging PRs until it was fixed, thanks for your patience.

**Review by BrianThomasRoss — APPROVED** [review]

**Comment by BrianThomasRoss** [comment]
Very nice work, and again sorry for the delay.

**Pull request merged**
