### PR TITLE
[dash] Fix #486 : Fix intro.py preventing i18n function

### LINKED ISSUE #486: ["dash"] intro.py & intro.md are interfering with localization function
### Description:

intro.py is generating sentences in the program, which interferes with the creation of localization resources.
Problems are here:
```
            infected_population_warning_str = (
                "(Warning:"
                " The number of estimated infections is greater than"
                " the total regional population."
                " Please verify the values entered in the sidebar.)"
                ""
                if model.infected > pars.population
                else ""
            )
```

```
                impact_statement=(
                    "halves the infections every"
                    if model.r_t < 1
                    else "reduces the doubling time to"
                ),
```

Please move these sentences into resource files.

In addition, don't create a resource that uses logic to determine the word order.
For example, a sentence like "reduces the doubling time to 2 days" in English, word order in Japanese is like "the doubling time 2 days to reduces".
So with the current implementation, Japanese resource is very tough to create.

My personal recommendation is to create two resources depending on the conditions, even though I know it will be redundant.
Like, 
```
rt_lessthan1: "**Mitigation**: A **{relative_contact_rate:.0%}** reduction in social contact after the onset of the outbreak **reduces the doubling time to {doubling_time_t:.1f}** days, implying an effective **`R(t)`** of **{r_t:.2f}** and daily growth rate of **{daily_growth_t:.2f}%**."
rt_morethanequal1: "**Mitigation**: A **{relative_contact_rate:.0%}** reduction in social contact after the onset of the outbreak **halves the infections every {doubling_time_t:.1f}** days, implying an effective **`R(t)`** of **{r_t:.2f}** and daily growth rate of **{daily_growth_t:.2f}%**."
```

[ ] This is something we can copy over from streamlit (screenshots if applicable)

### PR DESCRIPTION
**Pull request by kochizufan**
This PR is fixed issue #486.
Fixing that intro.py was preventing i18n function.

### CODE REVIEW

**Review by ckoerber — APPROVED** [review]
Hello @kochizufan,

Thank you for the `intro` i18n update. The changes look fine to me and brings the intro template files more in line with the other files.

I have tested changes locally and the PR addresses the issue.

**Review by BrianThomasRoss — APPROVED** [review]
Looks great thanks for your contribution.

**Comment by BrianThomasRoss** [comment]
@kochizufan This is just waiting on a being brought up to date with the base branch to merge, because it comes from an org I am unable to do so myself

**Comment by kochizufan** [comment]
Does that mean I have to do something additionally?
Or just waiting is OK?

**Comment by BrianThomasRoss** [comment]
> Does that mean I have to do something additionally?
> Or just waiting is OK?

You should just need to click the button here
image

I just can't do it myself since it's coming from another org

**Comment by kochizufan** [comment]
I did it!

**Comment by BrianThomasRoss** [comment]
Thanks!

**Pull request merged**
