### PR TITLE
makes census chart granular at daily level

### LINKED ISSUE #11: admitted patients (census) chart is weekly granular, should be daily
as per discussion in thread https://github.com/pennsignals/chime/pull/58 ,

it used to look like this 
76877593-0640cc80-684a-11ea-89ab-f5b1e7e2f279

now it looks like this
Screenshot from 2020-03-17 12-55-14

the granularity of the chart should be daily, not weekly, this detail has to be recovered from the matplotlib version.

### PR DESCRIPTION
**Pull request by fbenamy**
Closes #11

### CODE REVIEW

**Comment by cjbayesian** [comment]
Please merge in latest master in order to allow a side-by-side comparison of numbers with current prod.

**Comment by fbenamy** [comment]
@cjbayesian Just merged the current master into this branch.

**Comment by cjbayesian** [comment]
Thanks, @fbenamy . This looks like it's going to work, but there is code currently in this branch that is not the latest in terms of how the initial infected population is being calculated. Specifically, this input should not be there:
image

All of the code that is not related to the just the census chart should not differ between this and master.

**Comment by fbenamy** [comment]
That's very weird. I pulled from the Code for Philly master before merging. Let me do some digging and see what might be up with my local repo not staying current.

**Comment by fbenamy** [comment]
So it looks like I somehow removed app.py from the merge commit. I just checked that the code is right in the online repo.

**Pull request merged**
