### PR TITLE
#60 Initial tests

### PR DESCRIPTION
**Pull request by pjhoberman**
- Removed top level `__init__.py`
- Added tests:
  - sim_sir
  - initial_conditions
  - derived_variables
  - new_admissions_chart

### CODE REVIEW

**Comment by pjhoberman** [comment]
FYI this is just one of many pushes. I wanted to get this code to you to check style, to get some more tests up, and to push my code before my baby wakes up from his nap

**Comment by quinn-dougherty** [comment]
hi! if this is WIP could you please edit it's name and put WIP in there? 

also, could you go over for me how to run these tests locally?

**Comment by pjhoberman** [comment]
It’s more an initial push on a longer effort, but can be merged in as is.

Just run `pytest` from terminal and it should work. Let me know?

**Review by quinn-dougherty — APPROVED** [review]
all good

**Pull request merged**
