### PR TITLE
#147 Toggle presentation objects days<->dates

### PR DESCRIPTION
**Pull request by ckoerber**
I have added a function which converts days (ints) to actual dates for a given pandas DataFrame. For now, this function assumes `day=0 <-> now` (no timezone information, thus takes server time).

This function is called by each presentation object (chart and table) if the `as_date` flag is set in `app.py`.  The date-string format is controlled by a global variable in `presentation.py` (`DATE_FORMAT`).

I have tested the web display on my machine but have not yet coded up unittests. Existing unittests seem to run through without issues.

Please let me know if this matches expectations for #147.

### CODE REVIEW

**Comment by cjbayesian** [comment]
Just checked out locally. This meets the expectations of #147 . Could the mouseover on the graph data points also be presented as dates when that option is toggled on?

**Comment by quinn-dougherty** [comment]
heads up did some manual rebasing. verifying that i didn't ruin it in my local env right now
EDIT: all's well!

**Comment by quinn-dougherty** [comment]
Screenshot from 2020-03-21 09-33-47
@cjbayesian  is the staggered look ok? 

> Could the mouseover on the graph data points also be presented as dates when that option is toggled on? 

done

**Review by quinn-dougherty — APPROVED** [review]

**Comment by cjbayesian** [comment]
@quinn-dougherty Yes, the staggering is expected. 👍

**Pull request merged**
