### PR TITLE
Docs/release process

### PR DESCRIPTION
**Pull request by themightychris**

### CODE REVIEW

**Review by nickcanz — APPROVED** [review]
These changes look good! There are a few other places that need to updated to reflect `develop` being the main branch, but this is a good documentation of the release process.

**Comment by nickcanz** [comment]
Are the docs in the [chime live cluster](https://github.com/CodeForPhilly/chime/blob/develop/docs/operations/chime-live-cluster.md) file still accurate? I see one reference to `master` branch in there.

**Review by MooseQuest — COMMENTED** [review]
I suggest moving the PR template to it's own file.

**Comment by themightychris** [comment]
I hadn't considered actually adding a PR template for releases, that's a good idea but I want to test it out separately in a forked repo

**Pull request merged**
