### PR TITLE
Include currently-hospitalized patients in census

### LINKED ISSUE #187: Census should not start from 0
Currently, the census is computed by accumulating a proportion of _new_ cases, and discharging them after 'length of stay'. This does not account for the currently hospitalized cases, as can be seen by this example of setting current hospitalized cases to 4000:
image

The initial model assumed the starting point to be very early on when this had much less impact, however this will be increasingly important for localities that are further along in the course of spread.

### PR DESCRIPTION
**Pull request by PhilMiller**
The given number of current-hospitalized patients need to be included in the census, especially as peak load approaches, since they may still be in care when that happens.

They're pessimistically counted as all admitted on day 0. The number of ICU and ventilator patients is initialized in the same proportion to overall hospital population as newly infected patients would be.

Fixes: #187

### CODE REVIEW

**Comment by cjbayesian** [comment]
This approach is a good start though it leads to discontinuities in the census projection since the initial batch all discharge at the same time. It also leads to a spike at day zero admissions. For example:
image

**Comment by mdbecker** [comment]
@cjbayesian do you have any suggestions on what specific improvements you'd like to see before this gets merged?

**Comment by cjbayesian** [comment]
No, this might have to do for now. I'd like to keep a ticket open for improving the approach, however.

**Comment by PhilMiller** [comment]
The admissions chart may have to hide day zero if we want to not throw off its y-axis, or implement some compensating hack in the chart generation.

Until the model can more appropriately back-project or use hospitalization data beyond just "everyone here at day 0", I think the ugliness provides a clear signal that something weird is being done at day zero. On one hand, that would encourage people to be cautious with the model if their current hospitalization count puts them way along the infection curve. On the other hand, it risks undermining user trust because it's hard to explain.

**Comment by jordanclark397** [comment]
Why not just keep everything the way it is (zero patients on day zero) and then just translate the origin to a day that is approximately equal to the number of current admissions?

EDIT: You could also just add a faint reference line to the chart on whatever day is closest to the current number of admissions.

**Comment by PhilMiller** [comment]
I really like the second suggestion from @jordanclark397 of adding a reference line. That makes it easy for consumers to compare hospitalization levels before 'today' (the day the model is run) against their observations, and maybe tweak parameters accordingly

**Comment by cjbayesian** [comment]
@PhilMiller Yes, I think we start the admissions graph on day 1 rather than 0. It stills leaves the census discontinuity issue, but like I said above, I think it will do for now until we come up with a better way to account from pre-day 1 conditions/trajectories.

I think that @jordanclark397 's idea for just shifting the origin and lining up with current is the way to go, but will take some effort that's beyond this simple fix.

**Review by cjbayesian — CHANGES_REQUESTED** [review]
I recommend merging this if the admission plot can be set to start on day 1. It's not a perfect solution, but is an improvement over current state. We'll revisit the issue for a better solution targeted at the subsequent release.

**Comment by mdbecker** [comment]
@PhilMiller looks like there were some new updates from @cjbayesian above and this branch has come conflicts. Could you address those comments before we merge? Thanks!

**Comment by PhilMiller** [comment]
Tests all pass with my change, which suggests that there's currently no checking of the numbers coming out in `census_df`. I'll see to that before this should be merged, because there may be something horribly wrong.

**Comment by PhilMiller** [comment]
Ok, I was right to be suspicious of my code. The unchanged tests were passing because I'd screwed up the assignment to the dataframe. That's now fixed, and I've added tests of exactly the intent of this overall change.

I still want to add a disclaimer to the web UI about the discontinuity, so we don't get repeated questions about it.

**Comment by misken** [comment]
I'm working with a team for one of the big healthcare systems in SE Michigan. We've been using your model for the past week (awesome work, thank you) and have been grappling with census at time 0 issue as well. Right now the hospital folks are taking the x-axis translation approach and just interpreting chime output as time 0 being when projected census is close to current hospital census. I had some thoughts on another approach that tries to back into when t0 is for our region by matching admission rates and taking into account a stage where growth is at intrinsic rate and a stage where growth is at implicit rate based on modified doubling time due to distancing. All still rough but I sketch out the idea at [one of my GitHub repos](https://github.com/misken/c19). Hacked together an Excel version to talk through with some analysts and now I'll start to pythonize. Not sure if this is right place to be posting or if this idea is promising but figured I'd share.

**Comment by PhilMiller** [comment]
@misken Hi, thanks for commenting.

For current practice, do you mean (A) a y-axis translation approach, of adding on current patients? Or do you truly mean (B) time-shifting the projection to when the forecast census matches the current hospital census?

Approach (A) is reasonably well-founded, just tedious and requires manual data massage to not have the census graph make people disbelieve. The model is literally computing the census only of patients admitted from day 0 onward, but with a consistent view of the population dynamics.

Approach (B) applied naively will get the infection rates very wrong, since the current population proportions of susceptible and infected individuals is computed based on the current hospitalizations. #255 is about doing this much better, but we will potentially do this as a stop-gap. It looks like some solution to #255 is targeted for deployment Monday

**Comment by misken** [comment]
@PhilMiller - thanks for that update. Unfortunately, yes, the hospital is doing B right now (big hospital) because people were very uncomfortable with 0 census at t0 since hospital has many hundreds of covid patients. Looks like #255 is doing something similar to my suggestion to find a true t0 (either via user input or math) and admit matching (or census matching). Good to hear that may be available soon. I will pass along your concern about naive application of x-axis translation (B) and try to get my approach working as a post-processor for them until the real fix goes live next week. In your opinion, will, say a 5 day time shift lead to serious overestimation or underestimation of census?

**Comment by PhilMiller** [comment]
The total number of people who've been infected makes a logistic curve over time. Over or under-estimation depends on where on that curve you are - before or after the inflection point. That point matches the peak of new admissions, with some delay for how long people take to become symptomatic. Unfortunately, when we see that peak is exactly what we want to predict, because we can't observe it until it's past.

**Comment by misken** [comment]
yep, we are still in exponential growth stage before inflection point. Capacity going to be the limiting factor before the inflection point.

**Comment by PhilMiller** [comment]
This is superseded by the more advanced development of #255

**Pull request closed without merging**
