### PR TITLE
17 chart language

### LINKED ISSUE #17: Natural language summary of outputs
In addition to the output plots, it would help to have an automatically takeaway in words. For example:

Peak admissions projected in XX days.
ICU admissions projected to surpass XX in YY days.
...

### PR DESCRIPTION
**Pull request by pjhoberman**
See notes in #17. This is in draft for now.

### CODE REVIEW

**Comment by quinn-dougherty** [comment]
@pjhoberman  i'm gonna do the auto-update from here sooner rather than later, fetch it down please hope it doesn't cause conflict

**Comment by quinn-dougherty** [comment]
nvm it said there's a merge conflict already

**Comment by pjhoberman** [comment]
@quinn-dougherty rebased and re-pushed. It's in draft mode while I wait for feedback though

**Comment by sam-writer** [comment]
Just to check - there is a big formatting change as well, that is intentional? I see @mdbecker 's commit running black (is that part of CI/CD?) as part of this PR... just trying to understand that. 

About the real content of this PR - I like the way it is done. I have one code style thought, but nothing blocking. It seems like the only purpose of the second param, `def chart_descriptions(chart, census=False)` is 

```python
    if census:
        cols = [col + " Census" for col in cols]
```

it might be more extensible to just make the second parameter the word we want to add, eg `def chart_descriptions(chart, suffix="")` and do something like `if suffix != "": cols = [col + "  " + suffix for col in cols]`

But like I said, not blocking

**Comment by quinn-dougherty** [comment]
black is not in ci/cd yet https://github.com/CodeForPhilly/chime/issues/193

**Comment by pjhoberman** [comment]
@sam-qordoba The formatting updates are from the rebase. I'm not sure how to avoid pulling those commits in when I rebase - any thoughts?

I like the suffix idea. It's a bit fragile in that it's also related to the column name in the df. Trying to balance DRY. I can update that though!

**Comment by sam-writer** [comment]
@pjhoberman yeah I mean, it is still brittle so it might not matter. Just a thought.

@quinn-dougherty or @pjhoberman  or @mdbecker - is this the way that @mdbecker 's formatting changes are coming into the dev branch? or are his changes in another branch also? I am fine with either, just curious

**Review by sam-writer — APPROVED** [review]
LGTM

**Pull request merged**
