### PR TITLE
#132 Added tests around string and 0 values for sir fx

### LINKED ISSUE #132: Add to `test_sir`
Add to test_sir including edge cases. Ensure things that shouldn't work don't work (like negative numbers in some spots)

### PR DESCRIPTION
**Pull request by pjhoberman**

### CODE REVIEW

**Comment by pjhoberman** [comment]
Subtask of #60

**Comment by mariekers** [comment]
Python friends - will this work after the rewrite?

**Comment by jlubken** [comment]
Yeah this will work after the rewrite. This change has much to do with isolating the tests from the ui.

**Comment by jlubken** [comment]
@mariekers Yes, this will work after the rewrite. It is testing the model only.

**Review by jlubken — APPROVED** [review]

**Pull request merged**
