### PR TITLE
Updates to number input step, min val, and types

### LINKED ISSUE #269: Fix hover text in inputs
The hover text is inaccurate. For example for a value of 2.5, 'Hospitalization %' states: "Please enter a valid value. The two nearest valid values are 2.001 and 3.001"

I think the text is generated from the step parameter. Which isn't a bad value, but it is being used to generate the misleading text. Any other options we can add to the st.number_input to fix this?

### LINKED ISSUE #286: ["bug"] Improve Dockerfile layer caching
### Description:
The current order of steps in the Dockerfile has some expensive infrequent tasks (e.g., `pip install -q .`) occurring after more frequently modified file are copied (e.g., `src`). The breaks layer caching and causes image builds to take longer than necessary.

### Steps to reproduce:
1. Run `./script/server`
2. Modify a file in `./src`
3. Run `./script/update`

### Expected behavior:
The step `RUN pip install -q .` is cached

### What I got instead:
The step `RUN pip install -q .` needs to execute

### LINKED ISSUE #287: ["bug"] Market share no longer divided by 100 before creating Parameters object
# Description:
market_share is not divided by 100 before creating the `Parameters` object in `presentation.py` (`presentation.py` line 293 `market_share=market_share`). This results in the `Parameters` object containing values between 0 and 100 instead of the expected range of 0 to 1. 

### Steps to reproduce:
1. Run `./script/server`
2. Open CHIME in a browser

### Expected behavior:
`The estimated number of currently infected individuals is 3733. The 510 confirmed cases in the region imply a 14% rate of detection. This is based on current inputs for Hospitalizations (14), Hospitalization rate (2%), Region size (4119405), and Hospital market share (15%).`

### What I got instead:
`The estimated number of currently infected individuals is 3733. The 510 confirmed cases in the region imply a 1366% rate of detection. This is based on current inputs for Hospitalizations (14), Hospitalization rate (2%), Region size (4119405), and Hospital market share (1500%).`

### PR DESCRIPTION
**Pull request by ecsmyth**
All changes in  `./src/penn_chime/`
**Fixes for issue 269**
* `presentation.py` Updated min value and step for most number inputs.
* `presentation.py` Updated format for float inputs to display as float instead of as int.
* `defaults.py` Change Constants type for doubling_time and relative_contact_rate from int to float
* `settings.py`Change default doubling_time from int to float

**Cleanup**
* Removed unused imports in `presentation.py`

Fixes #269

### CODE REVIEW

**Comment by jlubken** [comment]
This looks good. I really like the float inputs. doubling_time float is useful.

I assume we're stuck with the less useful +/- steps for some of the controls, and there might not be a way to suppress the +/- buttons.

I don't know what cypress is doing, otherwise I'd approve.

**Comment by jlubken** [comment]
Ops says that all cypress tests are failing right now, so the PR isn't breaking anything that we can tell.

**Review by jlubken — APPROVED** [review]

**Comment by ecsmyth** [comment]
I haven't looked into the +/- controls. I'll do that today.

Cypress is failing since the step for regional population changed the post-click value isn't what is expected. I'll fix that today, too.

**Comment by ecsmyth** [comment]
PR now also Fixes #286, and #287

**Pull request merged**
